name: fall_24_flutter_course
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  dio: ^5.6.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  freezed_annotation: ^2.4.4
  http: ^1.2.2
  intl: ^0.19.0
  json_annotation: ^4.9.0
  provider: ^6.1.2
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.12
  json_serializable: ^6.8.0
  freezed: ^2.5.7
  integration_test:
    sdk: flutter


flutter:
  uses-material-design: true
