name: fall_24_flutter_course
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  build_runner: ^2.4.12
  dio: ^5.6.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  freezed_annotation: ^2.4.4
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  http: ^1.2.2
  intl: ^0.19.0
  json_annotation: ^4.9.0
  provider: ^6.1.2
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true
